spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      service-id: data
      enabled: true
    config:
      uri: http://localhost:8071
    loadbalancer:
      ribbon:
        enabled: false
